<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE furigana_test_kanji_dic [
<!ELEMENT furigana_test_kanji_dic (character*)>
<!ELEMENT character (literal , reading_meaning?)>
<!ELEMENT literal (#PCDATA)>
<!ELEMENT reading_meaning (rmgroup* , nanori*)>
<!ELEMENT rmgroup (reading*)>
<!ELEMENT reading (#PCDATA)>
<!ATTLIST reading r_type CDATA #REQUIRED>
<!ELEMENT nanori (#PCDATA)>
]>
<furigana_test_kanji_dic>
  <!-- Entry for Kanji: 𩺊 -->
  <character>
    <literal>𩺊</literal>
  </character>
  <!-- Entry for Kanji: 一 -->
  <character>
    <literal>一</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">イチ</reading>
        <reading r_type="ja_on">イツ</reading>
        <reading r_type="ja_kun">ひと-</reading>
        <reading r_type="ja_kun">ひと.つ</reading>
      </rmgroup>
      <nanori>かず</nanori>
      <nanori>い</nanori>
      <nanori>いっ</nanori>
      <nanori>いる</nanori>
      <nanori>かつ</nanori>
      <nanori>かづ</nanori>
      <nanori>てん</nanori>
      <nanori>はじめ</nanori>
      <nanori>ひ</nanori>
      <nanori>ひとつ</nanori>
      <nanori>まこと</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 京 -->
  <character>
    <literal>京</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">キョウ</reading>
        <reading r_type="ja_on">ケイ</reading>
        <reading r_type="ja_on">キン</reading>
        <reading r_type="ja_kun">みやこ</reading>
      </rmgroup>
      <nanori>たか</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 会 -->
  <character>
    <literal>会</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">カイ</reading>
        <reading r_type="ja_on">エ</reading>
        <reading r_type="ja_kun">あ.う</reading>
        <reading r_type="ja_kun">あ.わせる</reading>
        <reading r_type="ja_kun">あつ.まる</reading>
      </rmgroup>
      <nanori>あい</nanori>
      <nanori>い</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 余 -->
  <character>
    <literal>余</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ヨ</reading>
        <reading r_type="ja_kun">あま.る</reading>
        <reading r_type="ja_kun">あま.り</reading>
        <reading r_type="ja_kun">あま.す</reading>
        <reading r_type="ja_kun">あんま.り</reading>
      </rmgroup>
      <nanori>あまる</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 側 -->
  <character>
    <literal>側</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ソク</reading>
        <reading r_type="ja_kun">かわ</reading>
        <reading r_type="ja_kun">がわ</reading>
        <reading r_type="ja_kun">そば</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 偶 -->
  <character>
    <literal>偶</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">グウ</reading>
        <reading r_type="ja_kun">たま</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 兄 -->
  <character>
    <literal>兄</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ケイ</reading>
        <reading r_type="ja_on">キョウ</reading>
        <reading r_type="ja_kun">あに</reading>
      </rmgroup>
      <nanori>え</nanori>
      <nanori>せ</nanori>
      <nanori>よし</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 刀 -->
  <character>
    <literal>刀</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">トウ</reading>
        <reading r_type="ja_kun">かたな</reading>
        <reading r_type="ja_kun">そり</reading>
      </rmgroup>
      <nanori>き</nanori>
      <nanori>ち</nanori>
      <nanori>と</nanori>
      <nanori>わき</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 協 -->
  <character>
    <literal>協</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">キョウ</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 和 -->
  <character>
    <literal>和</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ワ</reading>
        <reading r_type="ja_on">オ</reading>
        <reading r_type="ja_on">カ</reading>
        <reading r_type="ja_kun">やわ.らぐ</reading>
        <reading r_type="ja_kun">やわ.らげる</reading>
        <reading r_type="ja_kun">なご.む</reading>
        <reading r_type="ja_kun">なご.やか</reading>
        <reading r_type="ja_kun">あ.える</reading>
      </rmgroup>
      <nanori>あい</nanori>
      <nanori>いず</nanori>
      <nanori>かず</nanori>
      <nanori>かつ</nanori>
      <nanori>かつり</nanori>
      <nanori>かづ</nanori>
      <nanori>たけ</nanori>
      <nanori>ち</nanori>
      <nanori>とも</nanori>
      <nanori>な</nanori>
      <nanori>にぎ</nanori>
      <nanori>まさ</nanori>
      <nanori>やす</nanori>
      <nanori>よし</nanori>
      <nanori>より</nanori>
      <nanori>わだこ</nanori>
      <nanori>わっ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 嗹 -->
  <character>
    <literal>嗹</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">レン</reading>
        <reading r_type="ja_kun">おしゃべり</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 回 -->
  <character>
    <literal>回</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">カイ</reading>
        <reading r_type="ja_on">エ</reading>
        <reading r_type="ja_kun">まわ.る</reading>
        <reading r_type="ja_kun">-まわ.る</reading>
        <reading r_type="ja_kun">-まわ.り</reading>
        <reading r_type="ja_kun">まわ.す</reading>
        <reading r_type="ja_kun">-まわ.す</reading>
        <reading r_type="ja_kun">まわ.し-</reading>
        <reading r_type="ja_kun">-まわ.し</reading>
        <reading r_type="ja_kun">もとお.る</reading>
        <reading r_type="ja_kun">か.える</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 坊 -->
  <character>
    <literal>坊</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ボウ</reading>
        <reading r_type="ja_on">ボッ</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 大 -->
  <character>
    <literal>大</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ダイ</reading>
        <reading r_type="ja_on">タイ</reading>
        <reading r_type="ja_kun">おお-</reading>
        <reading r_type="ja_kun">おお.きい</reading>
        <reading r_type="ja_kun">-おお.いに</reading>
      </rmgroup>
      <nanori>うふ</nanori>
      <nanori>お</nanori>
      <nanori>おう</nanori>
      <nanori>た</nanori>
      <nanori>たかし</nanori>
      <nanori>とも</nanori>
      <nanori>はじめ</nanori>
      <nanori>ひろ</nanori>
      <nanori>ひろし</nanori>
      <nanori>まさ</nanori>
      <nanori>まさる</nanori>
      <nanori>もと</nanori>
      <nanori>わ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 姉 -->
  <character>
    <literal>姉</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">シ</reading>
        <reading r_type="ja_kun">あね</reading>
        <reading r_type="ja_kun">はは</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 学 -->
  <character>
    <literal>学</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ガク</reading>
        <reading r_type="ja_kun">まな.ぶ</reading>
      </rmgroup>
      <nanori>たか</nanori>
      <nanori>のり</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 履 -->
  <character>
    <literal>履</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">リ</reading>
        <reading r_type="ja_kun">は.く</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 弄 -->
  <character>
    <literal>弄</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ロウ</reading>
        <reading r_type="ja_on">ル</reading>
        <reading r_type="ja_kun">いじく.る</reading>
        <reading r_type="ja_kun">ろう.する</reading>
        <reading r_type="ja_kun">いじ.る</reading>
        <reading r_type="ja_kun">ひねく.る</reading>
        <reading r_type="ja_kun">たわむ.れる</reading>
        <reading r_type="ja_kun">もてあそ.ぶ</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 張 -->
  <character>
    <literal>張</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">チョウ</reading>
        <reading r_type="ja_kun">は.る</reading>
        <reading r_type="ja_kun">-は.り</reading>
        <reading r_type="ja_kun">-ば.り</reading>
      </rmgroup>
      <nanori>はり</nanori>
      <nanori>わり</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 御 -->
  <character>
    <literal>御</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ギョ</reading>
        <reading r_type="ja_on">ゴ</reading>
        <reading r_type="ja_kun">おん-</reading>
        <reading r_type="ja_kun">お-</reading>
        <reading r_type="ja_kun">み-</reading>
      </rmgroup>
      <nanori>う</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 愈 -->
  <character>
    <literal>愈</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ユ</reading>
        <reading r_type="ja_kun">いよいよ</reading>
        <reading r_type="ja_kun">まさ.る</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 所 -->
  <character>
    <literal>所</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ショ</reading>
        <reading r_type="ja_kun">ところ</reading>
        <reading r_type="ja_kun">-ところ</reading>
        <reading r_type="ja_kun">どころ</reading>
        <reading r_type="ja_kun">とこ</reading>
      </rmgroup>
      <nanori>せ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 抑 -->
  <character>
    <literal>抑</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ヨク</reading>
        <reading r_type="ja_kun">おさ.える</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 捗 -->
  <character>
    <literal>捗</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">チョク</reading>
        <reading r_type="ja_on">ホ</reading>
        <reading r_type="ja_kun">はかど.る</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 掻 -->
  <character>
    <literal>掻</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ソウ</reading>
        <reading r_type="ja_kun">か.く</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 攫 -->
  <character>
    <literal>攫</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">カク</reading>
        <reading r_type="ja_kun">さら.う</reading>
        <reading r_type="ja_kun">つか.む</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 日 -->
  <character>
    <literal>日</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ニチ</reading>
        <reading r_type="ja_on">ジツ</reading>
        <reading r_type="ja_kun">ひ</reading>
        <reading r_type="ja_kun">-び</reading>
        <reading r_type="ja_kun">-か</reading>
      </rmgroup>
      <nanori>あ</nanori>
      <nanori>あき</nanori>
      <nanori>いる</nanori>
      <nanori>く</nanori>
      <nanori>くさ</nanori>
      <nanori>こう</nanori>
      <nanori>す</nanori>
      <nanori>たち</nanori>
      <nanori>に</nanori>
      <nanori>にっ</nanori>
      <nanori>につ</nanori>
      <nanori>へ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 月 -->
  <character>
    <literal>月</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ゲツ</reading>
        <reading r_type="ja_on">ガツ</reading>
        <reading r_type="ja_kun">つき</reading>
      </rmgroup>
      <nanori>おと</nanori>
      <nanori>がっ</nanori>
      <nanori>す</nanori>
      <nanori>ずき</nanori>
      <nanori>もり</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 木 -->
  <character>
    <literal>木</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ボク</reading>
        <reading r_type="ja_on">モク</reading>
        <reading r_type="ja_kun">き</reading>
        <reading r_type="ja_kun">こ-</reading>
      </rmgroup>
      <nanori>ぐ</nanori>
      <nanori>も</nanori>
      <nanori>もと</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 本 -->
  <character>
    <literal>本</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ホン</reading>
        <reading r_type="ja_kun">もと</reading>
      </rmgroup>
      <nanori>まと</nanori>
      <nanori>ごう</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 東 -->
  <character>
    <literal>東</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">トウ</reading>
        <reading r_type="ja_kun">ひがし</reading>
      </rmgroup>
      <nanori>あい</nanori>
      <nanori>あがり</nanori>
      <nanori>あずま</nanori>
      <nanori>あづま</nanori>
      <nanori>こち</nanori>
      <nanori>さき</nanori>
      <nanori>しの</nanori>
      <nanori>とお</nanori>
      <nanori>はる</nanori>
      <nanori>ひが</nanori>
      <nanori>もと</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 母 -->
  <character>
    <literal>母</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ボ</reading>
        <reading r_type="ja_kun">はは</reading>
        <reading r_type="ja_kun">も</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 湾 -->
  <character>
    <literal>湾</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ワン</reading>
        <reading r_type="ja_kun">いりえ</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 犇 -->
  <character>
    <literal>犇</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ホン</reading>
        <reading r_type="ja_kun">ひし.めく</reading>
        <reading r_type="ja_kun">ひしひし</reading>
        <reading r_type="ja_kun">はし.る</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 独 -->
  <character>
    <literal>独</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ドク</reading>
        <reading r_type="ja_on">トク</reading>
        <reading r_type="ja_kun">ひと.り</reading>
      </rmgroup>
      <nanori>どいつ</nanori>
      <nanori>どっ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 珠 -->
  <character>
    <literal>珠</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">シュ</reading>
        <reading r_type="ja_kun">たま</reading>
      </rmgroup>
      <nanori>す</nanori>
      <nanori>とも</nanori>
      <nanori>ま</nanori>
      <nanori>み</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 生 -->
  <character>
    <literal>生</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">セイ</reading>
        <reading r_type="ja_on">ショウ</reading>
        <reading r_type="ja_kun">い.きる</reading>
        <reading r_type="ja_kun">い.かす</reading>
        <reading r_type="ja_kun">い.ける</reading>
        <reading r_type="ja_kun">う.まれる</reading>
        <reading r_type="ja_kun">うま.れる</reading>
        <reading r_type="ja_kun">う.まれ</reading>
        <reading r_type="ja_kun">うまれ</reading>
        <reading r_type="ja_kun">う.む</reading>
        <reading r_type="ja_kun">お.う</reading>
        <reading r_type="ja_kun">は.える</reading>
        <reading r_type="ja_kun">は.やす</reading>
        <reading r_type="ja_kun">き</reading>
        <reading r_type="ja_kun">なま</reading>
        <reading r_type="ja_kun">なま-</reading>
        <reading r_type="ja_kun">な.る</reading>
        <reading r_type="ja_kun">な.す</reading>
        <reading r_type="ja_kun">む.す</reading>
        <reading r_type="ja_kun">-う</reading>
      </rmgroup>
      <nanori>あさ</nanori>
      <nanori>いき</nanori>
      <nanori>いく</nanori>
      <nanori>いけ</nanori>
      <nanori>うぶ</nanori>
      <nanori>うまい</nanori>
      <nanori>え</nanori>
      <nanori>おい</nanori>
      <nanori>ぎゅう</nanori>
      <nanori>くるみ</nanori>
      <nanori>ごせ</nanori>
      <nanori>さ</nanori>
      <nanori>じょう</nanori>
      <nanori>すぎ</nanori>
      <nanori>そ</nanori>
      <nanori>そう</nanori>
      <nanori>ちる</nanori>
      <nanori>なば</nanori>
      <nanori>にう</nanori>
      <nanori>にゅう</nanori>
      <nanori>ふ</nanori>
      <nanori>み</nanori>
      <nanori>もう</nanori>
      <nanori>よい</nanori>
      <nanori>りゅう</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 益 -->
  <character>
    <literal>益</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">エキ</reading>
        <reading r_type="ja_on">ヤク</reading>
        <reading r_type="ja_kun">ま.す</reading>
      </rmgroup>
      <nanori>まし</nanori>
      <nanori>ます</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 真 -->
  <character>
    <literal>真</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">シン</reading>
        <reading r_type="ja_kun">ま</reading>
        <reading r_type="ja_kun">ま-</reading>
        <reading r_type="ja_kun">まこと</reading>
      </rmgroup>
      <nanori>さな</nanori>
      <nanori>さね</nanori>
      <nanori>ただ</nanori>
      <nanori>ただし</nanori>
      <nanori>なお</nanori>
      <nanori>のり</nanori>
      <nanori>まあ</nanori>
      <nanori>まこ</nanori>
      <nanori>まさ</nanori>
      <nanori>まっ</nanori>
      <nanori>まど</nanori>
      <nanori>まな</nanori>
      <nanori>まゆ</nanori>
      <nanori>みち</nanori>
      <nanori>も</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 竹 -->
  <character>
    <literal>竹</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">チク</reading>
        <reading r_type="ja_kun">たけ</reading>
      </rmgroup>
      <nanori>たか</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 純 -->
  <character>
    <literal>純</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ジュン</reading>
      </rmgroup>
      <nanori>あつ</nanori>
      <nanori>すみ</nanori>
      <nanori>み</nanori>
      <nanori>やすし</nanori>
      <nanori>よし</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 者 -->
  <character>
    <literal>者</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">シャ</reading>
        <reading r_type="ja_kun">もの</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 芝 -->
  <character>
    <literal>芝</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">シ</reading>
        <reading r_type="ja_kun">しば</reading>
      </rmgroup>
      <nanori>こげ</nanori>
      <nanori>しは</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 草 -->
  <character>
    <literal>草</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ソウ</reading>
        <reading r_type="ja_kun">くさ</reading>
        <reading r_type="ja_kun">くさ-</reading>
        <reading r_type="ja_kun">-ぐさ</reading>
      </rmgroup>
      <nanori>そ</nanori>
      <nanori>や</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 葉 -->
  <character>
    <literal>葉</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ヨウ</reading>
        <reading r_type="ja_kun">は</reading>
      </rmgroup>
      <nanori>よ</nanori>
      <nanori>わ</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 薬 -->
  <character>
    <literal>薬</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ヤク</reading>
        <reading r_type="ja_kun">くすり</reading>
      </rmgroup>
      <nanori>み</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 製 -->
  <character>
    <literal>製</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">セイ</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 見 -->
  <character>
    <literal>見</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ケン</reading>
        <reading r_type="ja_kun">み.る</reading>
        <reading r_type="ja_kun">み.える</reading>
        <reading r_type="ja_kun">み.せる</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 路 -->
  <character>
    <literal>路</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ロ</reading>
        <reading r_type="ja_on">ル</reading>
        <reading r_type="ja_kun">-じ</reading>
        <reading r_type="ja_kun">みち</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 邪 -->
  <character>
    <literal>邪</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ジャ</reading>
        <reading r_type="ja_kun">よこし.ま</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 険 -->
  <character>
    <literal>険</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ケン</reading>
        <reading r_type="ja_kun">けわ.しい</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 頑 -->
  <character>
    <literal>頑</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">ガン</reading>
        <reading r_type="ja_kun">かたく.な</reading>
      </rmgroup>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 風 -->
  <character>
    <literal>風</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">フウ</reading>
        <reading r_type="ja_on">フ</reading>
        <reading r_type="ja_kun">かぜ</reading>
        <reading r_type="ja_kun">かざ-</reading>
      </rmgroup>
      <nanori>い</nanori>
      <nanori>え</nanori>
    </reading_meaning>
  </character>
  <!-- Entry for Kanji: 魂 -->
  <character>
    <literal>魂</literal>
    <reading_meaning>
      <rmgroup>
        <reading r_type="ja_on">コン</reading>
        <reading r_type="ja_kun">たましい</reading>
        <reading r_type="ja_kun">たま</reading>
      </rmgroup>
    </reading_meaning>
  </character>
</furigana_test_kanji_dic>
